### ISSUE TITLE
Did you freeze the new added token embeddings when finetuning?

### ISSUE THREAD

**Issue by Soistesimmer** [UKPLab/StructAdapt#1]
Hi! I find that the relation types in AMR graph are added to the T5 vocab. Did you also freeze their embeddings when finetuning?

**Comment by leoribeiro** [comment]
Hello,

We tried both embedding freezing and training the relations embeddings. Both performed comparable in our preliminar experiments.

**Comment by Soistesimmer** [comment]
Thank you for your reply! So, it also works well if the additional token embeddings for relation types are just randomly initialized, right? That's surprising!

**Comment by leoribeiro** [comment]
Correct, the relation embeddings are randomly initialized.

**Comment by Soistesimmer** [comment]
I see. Thank you very much!
